### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by gurisko** [garystafford/generator-node-restify-mongodb#1]
Operating System: OSX El Capitan 10.11.4
Node: v5.12.0
Yo: 1.8.4

```
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/templates/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Function.module.exports.sync (/usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/read-chunk/index.js:34:14)
    at copy (/usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/yeoman-generator/lib/actions/actions.js:38:27)
    at module.exports.yeoman.Base.extend.projectfiles (/usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/index.js:60:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/yeoman-generator/lib/base.js:432:9
    at tryOnImmediate (timers.js:534:15)
```

This is the tree that is being left in the working directory:

```
.
├── app
│   ├── models
│   └── routes
├── config
├── data
└── spec
```

**Comment by garystafford** [comment]
No one else has reported this issue. The .gitignore file is included in the template folder, listed on index.js file, and passes the unit test. What is in your '/usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/templates/' folder, currently?

**Comment by gurisko** [comment]
Simple `touch /usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/templates/.gitignore` solves the problem.

Few more notes:
- yes, unit tests are all passing in the cloned local repository,
- I installed the generator from npm

@garystafford To answer your question, this is what is in the folder:

```
/usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/templates/
├── Gruntfile.js
├── app
│   ├── models
│   │   ├── index.js
│   │   └── widget.js
│   └── routes
│       ├── index.js
│       ├── utilities.js
│       └── widget.js
├── app.js
├── config
│   └── config.js
├── data
│   └── widgets.json
├── db-connection.js
├── log.js
├── package.json
├── postman
│   ├── Widgets.postman_collection.json
│   └── localhost-restify.postman_environment.json
└── spec
    ├── utils_spec.js
    └── widget_spec.js
```

**Comment by garystafford** [comment]
Thank you for the feedback. Looks like you are missing both these '.' files.
    this.copy('.gitignore', '.gitignore');
    this.copy('.editorconfig', '.editorconfig');
I found this known issue with .gitignore. I will try the workaround and re-test:
[https://github.com/yeoman/generator/issues/812](https://github.com/yeoman/generator/issues/812)

**Comment by zakkatkk** [comment]
Still appears to be an issue. Fixed with workaround.
