### ISSUE TITLE
[npm package] .gitignore is missing from dist

### ISSUE THREAD

**Issue by ghost** [garystafford/generator-node-restify-mongodb#2]
Hey, I got an error during `yo node-restify-mongodb`.
(from terminal):
`Error: ENOENT: no such file or directory, open 'C:\Users\Carlos\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\generators\app\templates\.gitignore'`
Steps to reproduce:
`npm install -g yo generator-node-restify-mongodb`
`yo node-restify-mongodb`

Env:
OS: Windows 10 Pro x64 Anniversary Update [Version 10.0.14393]
NodeJs: v6.5.0 x64
npm: v3.10.3

When I looked at %appdata%\npm\node_modules\generator-node-restify-mongodb\generators\app\templates, the file .gitignore is missing, causing the error.

![sketch 5](https://cloud.githubusercontent.com/assets/12563647/18597069/2dc7758a-7c1a-11e6-8a0f-788579b766f8.png)

**Comment by jgontrum** [comment]
I can confirm this error in OS X. Interestingly, the file does exist in the repository and the call to copy it also seems valid.

**Comment by garystafford** [comment]
This issue came up once before. This is or was a known bug with Yeoman generators. I will look into it again: [https://github.com/yeoman/generator/issues/812](https://github.com/yeoman/generator/issues/812)

**Comment by garystafford** [comment]
Fixed in v0.2.0
