### ISSUE TITLE
 Unhandled 'error' event

### ISSUE THREAD

**Issue by yulian-zapata** [garystafford/generator-node-restify-mongodb#3]
I have this error

![screenshot from 2016-11-11 16-34-40](https://cloud.githubusercontent.com/assets/3279481/20231034/0db19ce6-a82d-11e6-9816-465dfa77b529.png)

my  version of yeoman is 1.8.5., npm 3.10.9 and node v4.4.4

you can help ?

**Comment by garystafford** [comment]
Should be fixed in v0.2.0. Give it a try. Just released.
